# workflow file:  .github\workflows\<workflow_name>.(yml|yaml)

# general structure
<global>:
  <something>:
<runner>:
  <jobs>:
    <job>:
      <steps>:
        <shell script | action>:
    <job>:
      <steps>:
        <shell script | action>:

# doc links
# 1: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# 2: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
# 3: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication

# reference
name: ''
on: push | [push, fork]
on:
  workflow_dispatch: # needed for manually running the workflow (in actions panel)
  schedule:
    - cron: '30 23 * * *' # UTC timezone only (https://github.com/actions/runner/issues/1423)
  pull_request | push:
    branches:
      - main
      - 'dev'
     tags:
      - v2
      - v1.*
    branches-ignore:
    tags-ignore:
env:
jobs:
  my_job_name:
    runs-on: ubuntu-(latest|24.04|22.04) | windows-(latest|2022|2019) | macos-(latest|12|13|14) # 1: #standard-github-hosted-runners-for-public-repositories
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    permissions: # 3: #permissions-for-the-github_token
      contents: none|read|write | read/write
    steps:
      # 1: #jobsjob_idsteps
      - uses: actions/checkout@v4
      
      - run:
      
      - name:
        run:
      
      - name:
        if: github.event.schedule != '30 5 * * 1,3'
        run:
      
      - name:
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: # above `with` in-play

${{
  github.event_name       # event that trigged the job
  github.repository       # repo name
  github.ref              # repo branch
  github.workspace        # repo files
  github.actor            # -
  runner.os               # server os
  job.status              # job status
  secrets.GITHUB_TOKEN    # needed for `git push`
  secrets.GIT_CREDENTIALS # -
}}
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# run node script at certain time, commit and push
name: sync
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
jobs:
  dome:
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: node index.js
    - run: |
        git config user.email "ahmdee18@gmail.com"
        git config user.name "m-ahmadi"
        git add .
        git commit -m "sync"
        git push origin main
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@