abs(x)
all(iterable)
any(iterable)
ascii(object)
bin(x)
bool(?x)
breakpoint(*args, **kws)
bytearray(?source, ?encoding, ?errors)
bytes(?source, ?encoding, ?errors)
callable(object)
chr(i)
@classmethod()
compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1)
complex(?real, ?imag)
delattr(object, name)
dict(**kwarg) | dict(mapping|iterable, **kwarg)
dir(?object)
divmod(a, b)
enumerate(iterable, start=0)
eval(expression, ?globals, ?locals)
exec(object, ?globals, ?locals)
filter(function, iterable)
float(?x)
format(value, ?format_spec)
frozenset(iterable)
getattr(object, name, ?default)
globals()
hasattr(object, name)
hash(object)
help(object)
hex(x)
id(object)
input(?prompt)
int(?x, ?base=10)
isinstance(object, classinfo)
issubclass(object, classinfo)
iter(object[, sentinel)
len(s)
list(iterable)
locals()
map(function, iterable, ...)
max(iterable, *, ?key, ?default) | max(arg1, arg2, *args, ?key)
memoryview(object)
min(iterable, *, ?key, ?default) | min(arg1, arg2, *args, ?key)
next(iterator, ?default)
object()
oct(x)
open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
ord(c)
pow(base, exp, ?mod)
print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)
property(fget=None, fset=None, fdel=None, doc=None)
range(stop) | range(start, stop, ?step)
repr(object)
reversed(seq)
round(number, ?ndigits)
set(?iterable)
setattr(object, name, value)
slice(stop) | slice(start, stop, ?step)
sorted(iterable, *, key=None, reverse=False)
@staticmethod()
str(object='') | str(object=b'', encoding='utf-8', errors='strict')
sum(iterable, /, start=0)
super(?type, ?object_or_type])
tuple(?iterable)
type(?iterable|object) | type(name, bases, dict, **kwds)
vars(?object)
zip(*iterables)
__import__(name, globals=None, locals=None, fromlist=(), level=0))