INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ null,
	/* p_cat` */ 'cpu',
	/* company */ null,
	/* model */ null,
	/* code name */ null,
	/* E_Status */ null,
	/* E_Launch Date */ null,
	/* E_Processor Number */ null,
	/* E_# of Cores */ null,
	/* E_# of Threads */ null,
	/* E_Clock Speed */ null,
	/* E_Max Turbo Frequency */ null,
	/* E_Cache */ null,
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ null,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ null,
	/* E_Instruction Set Extensions */ null,
	/* E_Embedded Options Available */ null,
	/* E_Lithography */ null,
	/* E_Max TDP */ null,
	/* E_Thermal Solution Specification */ null,
	/* E_Recommended Customer Price_BOX */ null,
	/* E_Recommended Customer Price_TRAY */ null,
	/* MS_Max Memory Size (dependent on memory type) */ null,
	/* MS_Memory Types */ null,
	/* MS_# of Memory Channels */ null,
	/* MS_Max Memory Bandwidth */ null,
	/* MS_ECC Memory Supported ‡ */ null,
	/* GS_Processor Graphics ‡ */ null,
	/* GS_Graphics Base Frequency */ null,
	/* GS_Graphics Max Dynamic Frequency */ null,
	/* GS_Intel® Quick Sync Video */ null,
	/* GS_Intel® InTru™ 3D Technology */ null,
	/* GS_Intel® Insider™ */ null,
	/* GS_Intel® Wireless Display */ null,
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ null,
	/* EO_PCI Express Configurations ‡ */ null,
	/* EO_Max # of PCI Express Lanes */ null,
	/* PS_Max CPU Configuration */ null,
	/* PS_TCASE */ null,
	/* PS_Package Size */ null,
	/* PS_Graphics and IMC Lithography */ null,
	/* PS_Sockets Supported */ null,
	/* PS_Low Halogen Options Available */ null,
	/* AT_Intel® Turbo Boost Technology ‡ */ null,
	/* AT_Intel® vPro Technology ‡ */ null,
	/* AT_Intel® Hyper-Threading Technology ‡ */ null,
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ null,
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ null,
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ null,
	/* AT_Intel® TSX-NI ‡ */ null,
	/* AT_Intel® 64 ‡ */ null,
	/* AT_Idle States */ null,
	/* AT_Enhanced Intel SpeedStep® Technology */ null,
	/* AT_Thermal Monitoring Technologies */ null,
	/* AT_Intel® Identity Protection Technology ‡ */ null,
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ null,
	/* Intel® DPT_Secure Key */ null,
	/* Intel® PPT_Trusted Execution Technology ‡ */ null,
	/* Intel® PPT_Anti-Theft Technology */ null,
	/* Intel® PPT_Execute Disable Bit ‡ */ null,
	/* img_1 */ null,
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ null,
	/* img_generation */ null,
	/* price */ null
);