/*!40101 SET NAMES utf8 */;

DROP TABLE IF EXISTS cpus;

CREATE TABLE cpus (
	`product_id` int(11) auto_increment,
	`cpu_id` int(11),
	`p_cat` varchar(15),
	`company` varchar(15),
	`model` varchar(100),
	`code name` varchar(50),
	`E_Status` varchar(20),
	`E_Launch Date` varchar(20),
	`E_Processor Number` varchar(20),
	`E_# of Cores` tinyint(2) unsigned,
	`E_# of Threads` tinyint(2) unsigned,
	`E_Clock_Speed` varchar(10),
	`E_Max Turbo Frequency` varchar(10),
	`E_Cache` varchar(10),
	`E_Intel® Smart Cache` varchar(10),
	`E_# of QPI Links` tinyint(2) unsigned,
	`E_DMI2` varchar(10),
	`E_Instruction Set` varchar(10),
	`E_Instruction Set Extensions` varchar(20),
	`E_Embedded Options Available` varchar(3),
	`E_Lithography` varchar(10),
	`E_Max TDP` varchar(10),
	`E_Thermal Solution Specification` varchar(20),
	`E_Recommended Customer Price_BOX` varchar(9),
	`E_Recommended Customer Price_TRAY` varchar(9),
	`MS_Max Memory Size (dependent on memory type)` varchar(10),
	`MS_Memory Types` varchar(50),
	`MS_# of Memory Channels` tinyint(2) unsigned,
	`MS_Max Memory Bandwidth` varchar(10),
	`MS_ECC Memory Supported ‡` varchar(3),
	`GS_Processor Graphics ‡` varchar(50),
	`GS_Graphics Base Frequency` varchar(10),
	`GS_Graphics Max Dynamic Frequency` varchar(10),
	`GS_Intel® Quick Sync Video` varchar(3),
	`GS_Intel® InTru™ 3D Technology` varchar(3),
	`GS_Intel® Insider™` varchar(3),
	`GS_Intel® Wireless Display` varchar(3),
	`GS_Intel® Clear Video HD Technology` varchar(3),
	`GS_# of Displays Supported ‡` tinyint(2) unsigned,
	`GS_Intel® Flexible Display Interface (Intel® FDI)` varchar(3),
	`EO_PCI Express Revision` varchar(10),
	`EO_PCI Express Configurations ‡` varchar(50),
	`EO_Max # of PCI Express Lanes` tinyint(2) unsigned,
	`PS_Max CPU Configuration` tinyint(2) unsigned,
	`PS_TCASE` varchar(10),
	`PS_Package Size` varchar(20),
	`PS_Graphics and IMC Lithography` varchar(10),
	`PS_Sockets Supported` varchar(50),
	`PS_Low Halogen Options Available` varchar(10),
	`AT_Intel® Turbo Boost Technology ‡` varchar(3),
	`AT_Intel® vPro Technology ‡` varchar(3),
	`AT_Intel® Hyper-Threading Technology ‡` varchar(3),
	`AT_Intel® Virtualization Technology (VT-x) ‡` varchar(3),
	`AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡` varchar(3),
	`AT_Intel® VT-x with Extended Page Tables (EPT) ‡` varchar(3),
	`AT_Intel® TSX-NI ‡` varchar(3),
	`AT_Intel® 64 ‡` varchar(3),
	`AT_Idle States` varchar(3),
	`AT_Enhanced Intel SpeedStep® Technology` varchar(3),
	`AT_Thermal Monitoring Technologies` varchar(3),
	`AT_Intel® Identity Protection Technology ‡` varchar(3),
	`AT_Intel® My WiFi Technology` varchar(3),
	`AT_Intel® Demand Based Switching` varchar(3),
	`AT_Intel® Smart Response Technology` varchar(3),
	`Intel® DPT_AES New Instructions` varchar(3),
	`Intel® DPT_Secure Key` varchar(3),
	`Intel® PPT_Trusted Execution Technology ‡` varchar(3),
	`Intel® PPT_Anti-Theft Technology` varchar(3),
	`Intel® PPT_Execute Disable Bit ‡` varchar(3),
	`img_1` varchar(200),
	`img_2` varchar(200),
	`img_3` varchar(200),
	`img_4` varchar(200),
	`img_5` varchar(200),
	`img_brand` varchar(200),
	`img_generation` varchar(200),
	`price` varchar(12),
	primary key (product_id)
);
ALTER TABLE cpus ADD INDEX (cpu_id, product_id);

INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 1,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4765T',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4765T',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '2 GHz',
	/* E_Max Turbo Frequency */ '3 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '35 W',
	/* E_Thermal Solution Specification */ 'PCG 2013A',
	/* E_Recommended Customer Price_BOX */ null,
	/* E_Recommended Customer Price_TRAY */ '$303.00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.2 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '66.35°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'YES',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'YES',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'YES',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4765T/i7-4765T.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);


INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 2,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4770',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4770',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '3.4 GHz',
	/* E_Max Turbo Frequency */ '3.9 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '84 W',
	/* E_Thermal Solution Specification */ 'PCG 2013D',
	/* E_Recommended Customer Price_BOX */ '$312,00',
	/* E_Recommended Customer Price_TRAY */ '$303.00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.2 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '72.72°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150, FCLGA1150, FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'YES',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'YES',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'YES',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4770/i7-4770.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);

INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 3,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4770K',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4770K',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '3.5 GHz',
	/* E_Max Turbo Frequency */ '3.9 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '84 W',
	/* E_Thermal Solution Specification */ 'PCG 2013D',
	/* E_Recommended Customer Price_BOX */ '$350,00',
	/* E_Recommended Customer Price_TRAY */ '$339,00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.25 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '72.72°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150, FCLGA1150, FCLGA1150, FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'NO',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'NO',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'NO',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ null,
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4770K/i7-4770K.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);


INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 4,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4770S',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4770S',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '3.1 GHz',
	/* E_Max Turbo Frequency */ '3.9 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'YES',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '65 W',
	/* E_Thermal Solution Specification */ 'PCG 2013C',
	/* E_Recommended Customer Price_BOX */ '$305,00',
	/* E_Recommended Customer Price_TRAY */ '$303,00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.2 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '71.35°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150, FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'YES',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'YES',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'YES',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4770S/i7-4770S.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);


INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 5,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4770T',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4770T',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '2.5 GHz',
	/* E_Max Turbo Frequency */ '3.7 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '45 W',
	/* E_Thermal Solution Specification */ 'PCG 2013B',
	/* E_Recommended Customer Price_BOX */ null,
	/* E_Recommended Customer Price_TRAY */ '$303,00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.2 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '71.45°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'YES',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'YES',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'YES',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4770T/i7-4770T.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);


INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 6,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4770R',
	/* code name */ 'Crystal Well',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4770R',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '3.2 GHz',
	/* E_Max Turbo Frequency */ '3.9 GHz',
	/* E_Cache */ '6 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '65 W',
	/* E_Thermal Solution Specification */ null,
	/* E_Recommended Customer Price_BOX */ null,
	/* E_Recommended Customer Price_TRAY */ null,
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3L-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; Iris&trade; Pro graphics 5200',
	/* GS_Graphics Base Frequency */ '200 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.3 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '66.45°C',
	/* PS_Package Size */ '37.5mm x 32mm x 1.65mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ null,
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'NO',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'NO',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ 'YES',
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'NO',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4770R/i7-4770R.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);


INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 7,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4771',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4771',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '3.5 GHz',
	/* E_Max Turbo Frequency */ '3.9 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '84 W',
	/* E_Thermal Solution Specification */ 'PCG 2013D',
	/* E_Recommended Customer Price_BOX */ '$320,00',
	/* E_Recommended Customer Price_TRAY */ '$314,00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.2 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '72°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150, FCLGA1150, FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'YES',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'YES',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'YES',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4771/i7-4771.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);


INSERT INTO cpus VALUES (
	/* product_id */ null,
	/* cpu_id */ 8,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel',
	/* model */ 'Core i7-4960X Extreme Edition',
	/* code name */ 'Ivy Bridge E',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q3'13",
	/* E_Processor Number */ 'i7-4960X',
	/* E_# of Cores */ 6,
	/* E_# of Threads */ 12,
	/* E_Clock Speed */ '3.6 GHz',
	/* E_Max Turbo Frequency */ '4 GHz',
	/* E_Cache */ null,
	/* E_Intel® Smart Cache */ '15 MB',
	/* E_# of QPI Links */ null,
	/* E_DMI2 */ '5 GT/s',
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE4.2, AVX, AES',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '130 W',
	/* E_Thermal Solution Specification */ null,
	/* E_Recommended Customer Price_BOX */ null,
	/* E_Recommended Customer Price_TRAY */ null,
	/* MS_Max Memory Size (dependent on memory type) */ '64 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600/1866',
	/* MS_# of Memory Channels */ 4,
	/* MS_Max Memory Bandwidth */ '59.7 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ null,
	/* GS_Graphics Base Frequency */ null,
	/* GS_Graphics Max Dynamic Frequency */ null,
	/* GS_Intel® Quick Sync Video */ null,
	/* GS_Intel® InTru™ 3D Technology */ null,
	/* GS_Intel® Insider™ */ null,
	/* GS_Intel® Wireless Display */ null,
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ null,
	/* EO_Max # of PCI Express Lanes */ 40,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '66.8°C',
	/* PS_Package Size */ '52.5mm x 45.0mm',
	/* PS_Graphics and IMC Lithography */ null,
	/* PS_Sockets Supported */ 'FCLGA2011, FCLGA2011',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ 'YES',
	/* AT_Intel® vPro Technology ‡ */ 'NO',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ null,
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ 'NO',
	/* AT_Intel® Smart Response Technology */ 'YES',
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ null,
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'NO',
	/* Intel® PPT_Anti-Theft Technology */ null,
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/3rd Generation/Core i7/i7-3770K/i7-3770K.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/3rd generation/3rd_gen.png',
	/* price */ '500,000'
);