// some of them:

ALLUSERSPROFILE: "C:\ProgramData"
APPDATA: "C:\Users\NYC\AppData\Roaming"
COMPUTERNAME: "NYC-PC"
ComSpec: "C:\Windows\system32\cmd.exe"
CommonProgramFiles: "C:\Program Files\Common Files"
CommonProgramFiles(x86): "C:\Program Files (x86)\Common Files"
CommonProgramW6432: "C:\Program Files\Common Files"
GIT_INSTALL_ROOT: "D:\Program Files\cmder\vendor\git-for-windows"
HOME: "C:\Users\NYC"
HOMEDRIVE: "C:"
HOMEPATH: "\Users\NYC"
INIT_CWD: "D:\xampp\htdocs\tc"
LANG: "en_US.UTF-8"
LOCALAPPDATA: "C:\Users\NYC\AppData\Local"
LOGONSERVER: "\\NYC-PC"
NODE: "C:\Program Files\nodejs\node.exe"
NODE_EXE: "C:\Program Files\nodejs\\node.exe"
NPM_CLI_JS: "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js"
NPM_PREFIX_NPM_CLI_JS: "C:\Users\NYC\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js"
NUMBER_OF_PROCESSORS: "4"
OS: "Windows_NT"
PATH: "..." // too long
PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC"
PLINK_PROTOCOL: "ssh"
PROCESSOR_ARCHITECTURE: "AMD64"
PROCESSOR_IDENTIFIER: "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel"
PROCESSOR_LEVEL: "6"
PROCESSOR_REVISION: "3c03"
PSModulePath: "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\"
PUBLIC: "C:\Users\Public"
Path: "..." // too long
ProgramData: "C:\ProgramData"
ProgramFiles: "C:\Program Files"
ProgramFiles(x86): "C:\Program Files (x86)"
ProgramW6432: "C:\Program Files"
SystemDrive: "C:"
SystemRoot: "C:\Windows"
TEMP: "C:\Users\NYC\AppData\Local\Temp"
TERM: "cygwin"
TMP: "C:\Users\NYC\AppData\Local\Temp"
USERDOMAIN: "NYC-PC"
USERNAME: "NYC"
USERPROFILE: "C:\Users\NYC"
architecture: "64"
architecture_bits: "64"
npm_config_cache: "C:\Users\NYC\AppData\Roaming\npm-cache"
npm_config_globalconfig: "C:\Users\NYC\AppData\Roaming\npm\etc\npmrc"
npm_config_globalignorefile: "C:\Users\NYC\AppData\Roaming\npm\etc\npmignore"
npm_config_init_license: "ISC"
npm_config_init_module: "C:\Users\NYC\.npm-init.js"
npm_config_init_version: "1.0.0"
npm_config_metrics_registry: "https://registry.npmjs.org/"
npm_config_node_gyp: "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
npm_config_node_version: "10.16.3"
npm_config_prefix: "C:\Users\NYC\AppData\Roaming\npm"
npm_config_registry: "https://registry.npmjs.org/"
npm_config_save_prefix: "^"
npm_config_scripts_prepend_node_path: "warn-only"
npm_config_searchlimit: "20"
npm_config_shell: "C:\Windows\system32\cmd.exe"
npm_config_tmp: "C:\Users\NYC\AppData\Local\Temp"
npm_config_user_agent: "npm/6.9.0 node/v10.16.3 win32 x64"
npm_config_userconfig: "C:\Users\NYC\.npmrc"
npm_config_viewer: "browser"
npm_execpath: "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js"
npm_lifecycle_event: "start"
npm_node_execpath: "C:\Program Files\nodejs\node.exe"
windir: "C:\Windows"