INSERT INTO motherboard VALUES (
	/* product_id */ null,
	/* p_cat` */ 'motherboard',
	/* company */ null,
	/* model */ null,
	/* rev */ null,
	/* chipset */ null,
	/* C_company */ null,
	/* C_socket */ null,
	/* C_cpuSupp_detail_1 */ null,
	/* C_cpuSupp_detail_2 */ null,
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ null,
	/* M_ddr3_upTo */ null,
	/* M_ddr3_bus */ null,
	/* M_ddr3_comment */ null,
	/* M_upTo */ null,
	/* M_architecture */ null,
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ null,
	/* M_supp_xmp_memory_modules */ null,
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ null,
	/* A_channel */ null,
	/* A_hd_audio */ null,
	/* A_supp_spdif_out */ null,
	/* A_supp_dolby®_home_theater */ null,
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* LAN_chip_1 */ null,
	/* LAN_chip_2 */ null,
	/* WCM_detail_1 */ null,
	/* WCM_detail_2 */ null,
	/* ES_pcie_x16_16x_num */ null,
	/* ES_pcie_x16_16x_name */ null,
	/* ES_pcie_x16_16x_comment */ null,
	/* ES_pcie_x16_8x_num */ null,
	/* ES_pcie_x16_8x_name */ null,
	/* ES_pcie_x16_8x_comment */ null,
	/* ES_pcie_x16_4x_num */ null,
	/* ES_pcie_x16_4x_name */ null,
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ null,
	/* ES_pcie_x1_num */ null,
	/* ES_pcie_x1_comment */ null,
	/* ES_pci */ null,
	/* Multi-Graphics Technology */ null,
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ null,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ null,
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ null,
	/* SI_chip-1_sata_3Gb/s_connector_num */ null,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_raid_supp */ null,
	/* SI_chip-1_raid_supp_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2_name */ null,
	/* SI_chip-2_num */ null,
	/* SI_chip-2_sata_6Gb/s_connector_num */ null,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ null,
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ null,
	/* SI_chip-2_esata_6Gb/s_connector_num */ null,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ null,
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ null,
	/* SI_chip-2_esata_6Gb/s_connector_comment */ null,
	/* SI_chip-2_raid_supp */ null,
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ null,
	/* USB_chip-1_ver */ null,
	/* USB_chip-1_port on the back panel */ null,
	/* USB_chip-1_port on the back panel_comment */ null,
	/* USB_chip-1_port available through the internal USB header */ null,
	/* USB_chip-2_name */ null,
	/* USB_chip-2_num */ null,
	/* USB_chip-2_upTo */ null,
	/* USB_chip-2_ver */ null,
	/* USB_chip-2_port on the back panel */ null,
	/* USB_chip-2_port available through the internal USB header */ null,
	/* USB_chip-2_comment */ null,
	/* USB_chip-3_name */ null,
	/* USB_chip-3_num */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ null,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ null,
	/* IEEE_1394_upTo */ null,
	/* IEEE_1394_ver */ null,
	/* IEEE_1394_port on the back panel */ null,
	/* IEEE 1394_port available through the internal IEEE 1394a header */ null,
	/* IIOC_24-pin ATX main power connector */ null,
	/* IIOC_8-pin ATX 12V power connector */ null,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ null,
	/* IIOC_SATA 3Gb/s connector */ null,
	/* IIOC_SAS 3Gb/s connector */ null,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ null,
	/* IIOC_system fan header */ null,
	/* IIOC_front panel header */ null,
	/* IIOC_front panel audio header */ null,
	/* IIOC_S/PDIF Out header */ null,
	/* IIOC_USB 3.0/2.0 header */ null,
	/* IIOC_USB 2.0/1.1 header */ null,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ null,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ null,
	/* IIOC_Trusted Platform Module (TPM) header */ null,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ null,
	/* BPC_CPU overclocking button */ null,
	/* BPC_BIOS switch button */ null,
	/* BPC_Clear CMOS button */ null,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ null,
	/* BPC_USB 2.0/1.1 port */ null,
	/* BPC_eSATA/USB Combo connector */ null,
	/* BPC_eSATA 6Gb/s connector */ null,
	/* BPC_RJ-45 port */ null,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ null,
	/* BPC_coaxial S/PDIF Out connector */ null,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ null,
	/* BPC_audio jacks_detail */ null,
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ null,
	/* HWM_System voltage detection */ null,
	/* HWM_CPU/System temperature detection */ null,
	/* HWM_CPU/System fan speed detection */ null,
	/* HWM_CPU overheating warning */ null,
	/* HWM_CPU/System fan fail warning */ null,
	/* HWM_CPU/System fan speed control */ null,
	/* HWM_CPU/System fan speed control_comment */ null,
	/* BIOS_detail_1 */ null,
	/* BIOS_detail_2 */ null,
	/* BIOS_detail_3 */ null,
	/* BIOS_detail_4 */ null,
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ null,
	/* UF_supp_Q-Flash */ null,
	/* UF_supp_Xpress BIOS Rescue */ null,
	/* UF_supp_Download Center */ null,
	/* UF_supp_Xpress Install */ null,
	/* UF_supp_Xpress Recovery2 */ null,
	/* UF_supp_EasyTune */ null,
	/* UF_supp_EasyTune_comment */ null,
	/* UF_supp_Smart 6™ */ null,
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ null,
	/* UF_supp_ON/OFF Charge */ null,
	/* UF_supp_Cloud OC */ null,
	/* UF_supp_TouchBIOS */ null,
	/* UF_supp_3TB+ Unlock */ null,
	/* UF_supp_Q-Share */ null,
	/* UF_supp_3D Power */ null,
	/* Bundle Software */ null,
	/* Operating System */ null,
	/* Form Factor */ null,
	/* Remark_1 */ null,
	/* Remark_2 */ null,
	/* img_1 */ null,
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ null,
	/* img_chipset */ null,
	/* price */ null
);