/*!40101 SET NAMES utf8 */;
DROP TABLE IF EXISTS motherboards;

CREATE TABLE motherboards (
	`product_id` int(11) auto_increment,
	`motherboard_id` int(11),
	`p_cat` varchar(15),
	`company` varchar(20),
	`model` varchar(20),
	`rev` decimal(2,1),
	`chipset` varchar(50),
	`C_company` varchar(20),
	`C_socket` varchar(20),
	`C_cpuSupp_detail_1` varchar(100),
	`C_cpuSupp_detail_2` varchar(100),
	`C_cpuSupp_detail_3` varchar(100),
	`C_cpuSupp_detail_4` varchar(100),
	`C_cpuSupp_detail_5` varchar(100),
	`M_ddr_slot` tinyint(2) unsigned,
	`M_ddr_upTo` tinyint(2) unsigned,
	`M_ddr_bus` varchar(100),
	`M_ddr_comment` varchar(500),
	`M_ddr2_slot` tinyint(2) unsigned,
	`M_ddr2_upTo` tinyint(2) unsigned,
	`M_ddr2_bus` varchar(100),
	`M_ddr2_comment` varchar(500),
	`M_ddr3_slot` tinyint(2) unsigned,
	`M_ddr3_upTo` tinyint(2) unsigned,
	`M_ddr3_bus` varchar(100),
	`M_ddr3_comment` varchar(500),
	`M_upTo` tinyint(2) unsigned,
	`M_architecture` varchar(20),
	`M_supp_unbuffered-ecc_memory_modules` varchar(10),
	`M_supp_non-ecc_memory_modules` varchar(10),
	`M_supp_xmp_memory_modules` varchar(10),
	`M_supp_xmp_memory_modules_comment` varchar(500),
	`A_chip` varchar(50),
	`A_channel` varchar(20),
	`A_hd_audio` varchar(10),
	`A_supp_spdif_out` varchar(10),
	`A_supp_dolby®_home_theater` varchar(10),
	`A_supp_eax®_advanced_hd™_5.0` varchar(10),
	`A_supp_x-fi_xtreme_fidelity®` varchar(10),
	`LAN_chip_1` varchar(50),
	`LAN_chip_2` varchar(50),
	`WCM_detail_1` varchar(50),
	`WCM_detail_2` varchar(50),
	`ES_pcie_x16_16x_num` tinyint(2) unsigned,
	`ES_pcie_x16_16x_name` varchar(20),
	`ES_pcie_x16_16x_comment` varchar(500),
	`ES_pcie_x16_8x_num` tinyint(2) unsigned,
	`ES_pcie_x16_8x_name` varchar(20),
	`ES_pcie_x16_8x_comment` varchar(500),
	`ES_pcie_x16_4x_num` tinyint(2) unsigned,
	`ES_pcie_x16_4x_name` varchar(20),
	`ES_pcie_x16_4x_comment` varchar(500),
	`ES_pcie_x16_comment` varchar(500),
	`ES_pcie_x1_num` tinyint(2) unsigned,
	`ES_pcie_x1_comment` varchar(500),
	`ES_pci` tinyint(2) unsigned,
	`Multi-Graphics Technology` varchar(200),
	`OG_IGP_d-sub_port` tinyint(2) unsigned,
	`OG_IGP_dvi-d_port_num` tinyint(2) unsigned,
	`OG_IGP_dvi-d_port_max_res` varchar(20),
	`OG_IGP_dvi-d_port_comment` varchar(400),
	`OG_IGP_hdmi_port_num` tinyint(2) unsigned,
	`OG_IGP_hdmi_port_max_res` varchar(20),
	`OG_IGP_displayport_num` tinyint(2) unsigned,
	`OG_IGP_displayport_max_res` varchar(20),
	`OG_chip-2_name` varchar(50),
	`OG_chip-2_thunderbolt_port_num` tinyint(2) unsigned,
	`OG_chip-2_thunderbolt_port_ver` varchar(40),
	`OG_chip-2_thunderbolt_port_max_res` varchar(20),
	`OG_chip-2_thunderbolt_port_supp_mini-displayport` varchar(10),
	`OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s)` varchar(10),
	`OG_chip-2_thunderbolt_port_comment` varchar(400),
	`SI_chip-1_sata_6Gb/s_connector_num` tinyint(2) unsigned,
	`SI_chip-1_sata_6Gb/s_connector_ver` varchar(20),
	`SI_chip-1_sata_6Gb/s_connector_upTo` varchar(20),
	`SI_chip-1_sata_3Gb/s_connector_num` tinyint(2) unsigned,
	`SI_chip-1_sata_3Gb/s_connector_ver` varchar(20),
	`SI_chip-1_sata_3Gb/s_connector_upTo` varchar(20),
	`SI_chip-1_raid_supp` varchar(50),
	`SI_chip-1_raid_supp_comment` varchar(500),
	`SI_chip-1_sas_3Gb/s_connector_num` tinyint(2) unsigned,
	`SI_chip-1_sas_3Gb/s_connector_ver` varchar(20),
	`SI_chip-1_sas_3Gb/s_connector_upTo` varchar(20),
	`SI_chip-1_sas_3Gb/s_connector_comment` varchar(200),
	`SI_chip-1_sas_3Gb/s_connector_raid_supp` varchar(50),
	`SI_chip-2_name` varchar(50),
	`SI_chip-2_num` tinyint(2),
	`SI_chip-2_sata_6Gb/s_connector_num` tinyint(2) unsigned,
	`SI_chip-2_sata_6Gb/s_connector_ver` varchar(20),
	`SI_chip-2_sata_6Gb/s_connector_upTo` varchar(20),
	`SI_chip-2_esata_6Gb/s_connector_num` tinyint(2) unsigned,
	`SI_chip-2_esata_6Gb/s_connector_ver/info` varchar(50),
	`SI_chip-2_esata_6Gb/s_connector_upTo` varchar(20),
	`SI_chip-2_esata_6Gb/s_connector_comment` varchar(100),
	`SI_chip-2_raid_supp` varchar(50),
	`SI_chip-2_raid_supp_comment` varchar(500),
	`SI_sata_6Gb/s_connector_num` tinyint(2) unsigned,
	`SI_sata_3Gb/s_connector_num` tinyint(2) unsigned,
	`SI_sas_3Gb/s_connector_num` tinyint(2) unsigned,
	`SI_esata_6Gb/s_connector_num` tinyint(2) unsigned,
	`USB_chip-1_upTo` tinyint(2) unsigned,
	`USB_chip-1_ver` varchar(20),
	`USB_chip-1_port on the back panel` tinyint(2) unsigned,
	`USB_chip-1_port on the back panel_comment` varchar(200),
	`USB_chip-1_port available through the internal USB header` tinyint(2) unsigned,
	`USB_chip-2_name` varchar(50),
	`USB_chip-2_num` tinyint(2) unsigned,
	`USB_chip-2_upTo` tinyint(2) unsigned,
	`USB_chip-2_ver` varchar(20),
	`USB_chip-2_port on the back panel` tinyint(2) unsigned,
	`USB_chip-2_port available through the internal USB header` tinyint(2) unsigned,
	`USB_chip-2_comment` varchar(500),
	`USB_chip-3_name` varchar(50),
	`USB_chip-3_num` tinyint(2) unsigned,
	`USB_chip-3_upTo` tinyint(2) unsigned,
	`USB_chip-3_ver` varchar(20),
	`USB_chip-3_port on the back panel` tinyint(2) unsigned,
	`USB_chip-3_port available through the internal USB header` tinyint(2) unsigned,
	`USB_2.0/1.1` tinyint(2) unsigned,
	`USB_3.0/2.0` tinyint(2) unsigned,
	`IEEE_1394_chip` varchar(20),
	`IEEE_1394_upTo` tinyint(2) unsigned,
	`IEEE_1394_ver` varchar(20),
	`IEEE_1394_port on the back panel` tinyint(2) unsigned,
	`IEEE_1394_port available through the internal IEEE 1394a header` tinyint(2) unsigned,
	`IIOC_24-pin ATX main power connector` tinyint(2) unsigned,
	`IIOC_8-pin ATX 12V power connector` tinyint(2) unsigned,
	`IIOC_4-pin ATX 12V power connector` tinyint(2) unsigned,
	`IIOC_PCIe power connector` tinyint(2) unsigned,
	`IIOC_SATA 6Gb/s connector` tinyint(2) unsigned,
	`IIOC_SATA 3Gb/s connector` tinyint(2) unsigned,
	`IIOC_SAS 3Gb/s connector` tinyint(2) unsigned,
	`IIOC_mSATA connector` tinyint(2) unsigned,
	`IIOC_CPU fan header` tinyint(2) unsigned,
	`IIOC_system fan header` tinyint(2) unsigned,
	`IIOC_front panel header` tinyint(2) unsigned,
	`IIOC_front panel audio header` tinyint(2) unsigned,
	`IIOC_S/PDIF Out header` tinyint(2) unsigned,
	`IIOC_USB 3.0/2.0 header` tinyint(2) unsigned,
	`IIOC_USB 2.0/1.1 header` tinyint(2) unsigned,
	`IIOC_IEEE 1394a header` tinyint(2) unsigned,
	`IIOC_serial port header` tinyint(2) unsigned,
	`IIOC_parallel port` tinyint(2) unsigned,
	`IIOC_chassis intrusion header` tinyint(2) unsigned,
	`IIOC_digital microphone header` tinyint(2) unsigned,
	`IIOC_speaker header` tinyint(2) unsigned,
	`IIOC_AIO speaker header` tinyint(2) unsigned,
	`IIOC_LVDS drive voltage header` tinyint(2) unsigned,
	`IIOC_LVDS connector` tinyint(2) unsigned,
	`IIOC_flat panel display power header` tinyint(2) unsigned,
	`IIOC_flat panel display power connector` tinyint(2) unsigned,
	`IIOC_flat panel display switch header` tinyint(2) unsigned,
	`IIOC_backlight switch header` tinyint(2) unsigned,
	`IIOC_WIFI activity indicator LED header` tinyint(2) unsigned,
	`IIOC_Clear CMOS jumper` tinyint(2) unsigned,
	`IIOC_Trusted Platform Module (TPM) header` tinyint(2) unsigned,
	`IIOC_onboard voltage measurement module` tinyint(2) unsigned,
	`IIOC_Voltage Measurement Points` tinyint(2) unsigned,
	`IIOC_power button` tinyint(2) unsigned,
	`IIOC_reset button` tinyint(2) unsigned,
	`IIOC_Clear CMOS button` tinyint(2) unsigned,
	`IIOC_Gear button` tinyint(2) unsigned,
	`IIOC_CPU BCLK Down button` tinyint(2) unsigned,
	`IIOC_CPU BCLK Up button` tinyint(2) unsigned,
	`IIOC_CPU Ratio Down button` tinyint(2) unsigned,
	`IIOC_CPU Ratio Up button` tinyint(2) unsigned,
	`IIOC_BIOS Switch` tinyint(2) unsigned,
	`IIOC_LN2 switch` tinyint(2) unsigned,
	`BPC_PS/2 keyboard port` tinyint(2) unsigned,
	`BPC_PS/2 mouse port` tinyint(2) unsigned,
	`BPC_PS/2 keyboard/mouse port` tinyint(2) unsigned,
	`BPC_CPU overclocking button` tinyint(2) unsigned,
	`BPC_BIOS switch button` tinyint(2) unsigned,
	`BPC_Clear CMOS button` tinyint(2) unsigned,
	`BPC_IEEE 1394a port` tinyint(2) unsigned,
	`BPC_USB 3.0/2.0 port` tinyint(2) unsigned,
	`BPC_USB 2.0/1.1 port` tinyint(2) unsigned,
	`BPC_eSATA/USB Combo connector` tinyint(2) unsigned,
	`BPC_eSATA 6Gb/s connector` tinyint(2) unsigned,
	`BPC_RJ-45 port` tinyint(2) unsigned,
	`BPC_parallel port` tinyint(2) unsigned,
	`BPC_serial port` tinyint(2) unsigned,
	`BPC_optical S/PDIF Out connector` tinyint(2) unsigned,
	`BPC_coaxial S/PDIF Out connector` tinyint(2) unsigned,
	`BPC_DC-In power connector` tinyint(2) unsigned,
	`BPC_audio jacks` tinyint(2) unsigned,
	`BPC_audio jacks_detail` varchar(200),
	`BPC_D-Sub port` tinyint(2) unsigned,
	`BPC_DVI-D port` tinyint(2) unsigned,
	`BPC_HDMI port` tinyint(2) unsigned,
	`BPC_DisplayPort` tinyint(2) unsigned,
	`I/O Controller` varchar(50),
	`HWM_System voltage detection` varchar(10),
	`HWM_CPU/System temperature detection` varchar(10),
	`HWM_CPU/System fan speed detection` varchar(10),
	`HWM_CPU overheating warning` varchar(10),
	`HWM_CPU/System fan fail warning` varchar(10),
	`HWM_CPU/System fan speed control` varchar(10),
	`HWM_CPU/System fan speed control_comment` varchar(500),
	`BIOS_detail_1` varchar(100),
	`BIOS_detail_2` varchar(100),
	`BIOS_detail_3` varchar(100),
	`BIOS_detail_4` varchar(100),
	`BIOS_detail_5` varchar(100),
	`UF_supp_@BIOS` varchar(10),
	`UF_supp_Q-Flash` varchar(10),
	`UF_supp_Xpress BIOS Rescue` varchar(10),
	`UF_supp_Download Center` varchar(10),
	`UF_supp_Xpress Install` varchar(10),
	`UF_supp_Xpress Recovery2` varchar(10),
	`UF_supp_EasyTune` varchar(10),
	`UF_supp_EasyTune_comment` varchar(200),
	`UF_supp_Smart 6™` varchar(10),
	`UF_supp_eXtreme Hard Drive (X.H.D)` varchar(10),
	`UF_supp_ON/OFF Charge` varchar(10),
	`UF_supp_Cloud OC` varchar(10),
	`UF_supp_TouchBIOS` varchar(10),
	`UF_supp_3TB+ Unlock` varchar(10),
	`UF_supp_Q-Share` varchar(10),
	`UF_supp_3D Power` varchar(10),
	`Bundle Software` varchar(500),
	`Operating System` varchar(200),
	`Form Factor` varchar(50),
	`Remark_1` varchar(500),
	`Remark_2` varchar(500),
	`img_1` varchar(100),
	`img_2` varchar(100),
	`img_3` varchar(100),
	`img_4` varchar(100),
	`img_5` varchar(100),
	`img_6` varchar(100),
	`img_7` varchar(100),
	`img_8` varchar(100),
	`img_9` varchar(100),
	`img_10` varchar(100),
	`img_brand` varchar(100),
	`img_chipset` varchar(100),
	`price` varchar(12),
	primary key (product_id)
);
ALTER TABLE motherboards ADD INDEX (product_id, motherboard_id);

INSERT INTO motherboards VALUES (
	/* product_id */ null,
	/* motherboard_id */ 1,
	/* p_cat` */ 'motherboard',
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UD5',
	/* rev */ 1.1,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_company */ 'INTEL',
	/* C_socket */ '2011',
	/* C_cpuSupp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_cpuSupp_detail_2 */ 'L3 cache varies with CPU',
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 8,
	/* M_ddr3_upTo */ 64,
	/* M_ddr3_bus */ '2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than 4 GB.',
	/* M_upTo */ 64,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC898',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ 'YES',
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* LAN_chip_1 */ 'Intel GbE LAN (10/100/1000 Mbit)',
	/* LAN_chip_2 */ null,
	/* WCM_detail_1 */ 'Wi-Fi 802.11 b/g/n',
	/* WCM_detail_2 */ 'Bluetooth 4.0, 3.0+HS, 2.1+EDR',
	/* ES_pcie_x16_16x_num */ 2,
	/* ES_pcie_x16_16x_name */ 'PCIEX16_1/PCIEX16_2',
	/* ES_pcie_x16_16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16_1 slot; if you are installing two PCI Express graphics cards, it is recommended that you install them in the PCIEX16_1 and PCIEX16_2 slots.',
	/* ES_pcie_x16_8x_num */ 1,
	/* ES_pcie_x16_8x_name */ 'PCIEX8',
	/* ES_pcie_x16_8x_comment */ null,
	/* ES_pcie_x16_4x_num */ null,
	/* ES_pcie_x16_4x_name */ null,
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci */ 1,
	/* Multi-Graphics Technology */ 'Support for 3-Way/2-Way AMD CrossFireX™ / NVIDIA SLI technology.',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/SATA2.5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2_name */ 'Marvell 88SE9172',
	/* SI_chip-2_num */ 1,
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'GSATA3.6/GSATA3.9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ 'on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_comment */ 'including 1 eSATA/USB Combo',
	/* SI_chip-2_raid_supp */ 'RAID 0, RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_port on the back panel */ 8,
	/* USB_chip-1_port on the back panel_comment */ 'including 1 eSATA/USB Combo',
	/* USB_chip-1_port available through the internal USB header */ 6,
	/* USB_chip-2_name */ 'Fresco FL1009',
	/* USB_chip-2_num */ 2,
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_port on the back panel */ 2,
	/* USB_chip-2_port available through the internal USB header */ 2,
	/* USB_chip-2_comment */ null,
	/* USB_chip-3_name */ null,
	/* USB_chip-3_num */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ null,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ 'VT6308',
	/* IEEE_1394_upTo */ 2,
	/* IEEE_1394_ver */ '1394a ports',
	/* IEEE_1394_port on the back panel */ 1,
	/* IEEE 1394_port available through the internal IEEE 1394a header */ 1,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_SAS 3Gb/s connector */ null,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ 1,
	/* IIOC_serial port header */ null,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ 1,
	/* BPC_BIOS switch button */ 1,
	/* BPC_Clear CMOS button */ 1,
	/* BPC_IEEE 1394a port */ 1,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 7,
	/* BPC_eSATA/USB Combo connector */ 1,
	/* BPC_eSATA 6Gb/s connector */ 1,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ null,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 5,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out, Rear Speaker Out, Side Speaker Out, Line In/Mic In, Line Out',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE IT8728 chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_CPU/System fan speed control_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS&trade;',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ 'YES',
	/* UF_supp_Download Center */ 'YES',
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ 'YES',
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_EasyTune_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* UF_supp_Smart 6™ */ 'YES',
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ 'YES',
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ 'YES',
	/* UF_supp_TouchBIOS */ 'YES',
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ null,
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft&reg; Windows 8/7/Vista/XP',
	/* Form Factor */ 'E-ATX Form Factor; 30.5cm x 26.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD5/1.jpg',
	/* img_2 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD5/2.jpg',
	/* img_3 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD5/3.jpg',
	/* img_4 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD5/4.jpg',
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/products/motherboard/brand/GIGABYTE_LOGO.png',
	/* img_chipset */ 'images/products/motherboard/brand/INTEL_X79_chipset.png',
	/* price */ '750,000'
);

INSERT INTO motherboards VALUES (
	/* product_id */ null,
	/* motherboard_id */ 2,
	/* p_cat` */ 'motherboard',
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UP4',
	/* rev */ 1.1,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_company */ 'INTEL',
	/* C_socket */ '2011',
	/* C_cpuSupp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_cpuSupp_detail_2 */ 'L3 cache varies with CPU',
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 8,
	/* M_ddr3_upTo */ 64,
	/* M_ddr3_bus */ '2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to a Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than the size of the physical memory installed.',
	/* M_upTo */ 64,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC892',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ null,
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* LAN_chip_1 */ 'Intel GbE LAN chip (10/100/1000 Mbit)',
	/* LAN_chip_2 */ null,
	/* WCM_detail_1 */ null,
	/* WCM_detail_2 */ null,
	/* ES_pcie_x16_16x_num */ 2,
	/* ES_pcie_x16_16x_name */ 'PCIEX16_1, PCIEX16_2',
	/* ES_pcie_x16_16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16 slot.',
	/* ES_pcie_x16_8x_num */ 2,
	/* ES_pcie_x16_8x_name */ 'PCIEX8_1, PCIEX8_2',
	/* ES_pcie_x16_8x_comment */ 'The PCIEX8_2 slot shares bandwidth with the PCIEX16_2 slot. When the PCIEX8_2 slot is populated, the PCIEX16_2 slot will operate at up to x8 mode.',
	/* ES_pcie_x16_4x_num */ null,
	/* ES_pcie_x16_4x_name */ null,
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci */ 1,
	/* Multi-Graphics Technology */ 'Support for 4-Way/3-Way/2-Way AMD CrossFireX™/NVIDIA SLI technology',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/SATA2.5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2_name */ 'Marvell 88SE9172',
	/* SI_chip-2_num */ 1,
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'SATA3.6/SATA3.9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ 'on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_comment */ null,
	/* SI_chip-2_raid_supp */ 'RAID 0, RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_port on the back panel */ 8,
	/* USB_chip-1_port on the back panel_comment */ null,
	/* USB_chip-1_port available through the internal USB header */ 8,
	/* USB_chip-2_name */ 'Fresco FL1009',
	/* USB_chip-2_num */ 2,
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0 ports',
	/* USB_chip-2_port on the back panel */ 2,
	/* USB_chip-2_port available through the internal USB header */ 2,
	/* USB_chip-2_comment */ null,
	/* USB_chip-3_name */ null,
	/* USB_chip-3_num */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ null,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ null,
	/* IEEE_1394_upTo */ null,
	/* IEEE_1394_ver */ null,
	/* IEEE_1394_port on the back panel */ null,
	/* IEEE_1394_port available through the internal IEEE 1394a header */ null,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_SAS 3Gb/s connector */ null,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ 1,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ null,
	/* BPC_BIOS switch button */ null,
	/* BPC_Clear CMOS button */ null,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 8,
	/* BPC_eSATA/USB Combo connector */ null,
	/* BPC_eSATA 6Gb/s connector */ 2,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ 1,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 6,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out/Rear Speaker Out/Side Speaker Out/Line In/Line Out/Microphone',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE I/O Controller Chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_CPU/System fan speed control_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS&trade;',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ null,
	/* UF_supp_Download Center */ null,
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ null,
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_EasyTune_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* UF_supp_Smart 6™ */ null,
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ null,
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ null,
	/* UF_supp_TouchBIOS */ null,
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_Q-Share */ null,
	/* UF_supp_3D Power */ 'YES',
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft&reg; Windows 8/7/Vista/XP',
	/* Form Factor */ 'ATX Form Factor; 30.5cm x 24.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/products/motherboard/GIGABYTE/GA-X79-UP4/1.jpg',
	/* img_2 */ 'images/products/motherboard/GIGABYTE/GA-X79-UP4/2.jpg',
	/* img_3 */ 'images/products/motherboard/GIGABYTE/GA-X79-UP4/3.jpg',
	/* img_4 */ 'images/products/motherboard/GIGABYTE/GA-X79-UP4/4.jpg',
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/products/motherboard/brand/GIGABYTE_LOGO.png',
	/* img_chipset */ 'images/products/motherboard/brand/INTEL_X79_chipset.png',
	/* price */ '650,000'
);

INSERT INTO motherboards VALUES (
	/* product_id */ null,
	/* motherboard_id */ 3,
	/* p_cat` */ 'motherboard',
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UD3',
	/* rev */ 1.1,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_company */ 'INTEL',
	/* C_socket */ '2011',
	/* C_cpuSupp_detail_1 */ 'Support for Intel® Core™ i7 processors in the LGA2011 package package',
	/* C_cpuSupp_detail_2 */ 'L3 cache varies with CPU',
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 4,
	/* M_ddr3_upTo */ 32,
	/* M_ddr3_bus */ '2400/2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than 4 GB.',
	/* M_upTo */ 32,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC898',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ 'YES',
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* LAN_chip_1 */ 'Intel GbE LAN (10/100/1000 Mbit)',
	/* LAN_chip_2 */ null,
	/* WCM_detail_1 */ null,
	/* WCM_detail_2 */ null,
	/* ES_pcie_x16_16x_num */ 2,
	/* ES_pcie_x16_16x_name */ 'PCIEX16_1, PCIEX16_2',
	/* ES_pcie_x16_16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16 slot.',
	/* ES_pcie_x16_8x_num */ 2,
	/* ES_pcie_x16_8x_name */ 'PCIEX8_1, PCIEX8_2',
	/* ES_pcie_x16_8x_comment */ 'The PCIEX8_2 slot shares bandwidth with the PCIEX16_2 slot. When the PCIEX8_2 slot is populated, the PCIEX16_2 slot will operate at up to x8 mode.',
	/* ES_pcie_x16_4x_num */ null,
	/* ES_pcie_x16_4x_name */ null,
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci */ 1,
	/* Multi-Graphics Technology */ 'Support for 4-Way/3-Way/2-Way AMD CrossFireX™/NVIDIA SLI technology.',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/3/4/5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2_name */ 'Marvell 88SE9172',
	/* SI_chip-2_num */ 1,
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'GSATA3.6/7/8/9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ 'on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_comment */ null,
	/* SI_chip-2_raid_supp */ 'RAID 0, RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_port on the back panel */ 8,
	/* USB_chip-1_port on the back panel_comment */ null,
	/* USB_chip-1_port available through the internal USB header */ 6,
	/* USB_chip-2_name */ 'Fresco FL1009',
	/* USB_chip-2_num */ 2,
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_port on the back panel */ 2,
	/* USB_chip-2_port available through the internal USB header */ 2,
	/* USB_chip-2_comment */ null,
	/* USB_chip-3_name */ null,
	/* USB_chip-3_num */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ null,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ null,
	/* IEEE_1394_upTo */ null,
	/* IEEE_1394_ver */ null,
	/* IEEE_1394_port on the back panel */ null,
	/* IEEE_1394_port available through the internal IEEE 1394a header */ null,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_SAS 3Gb/s connector */ null,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ 1,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ null,
	/* BPC_BIOS switch button */ null,
	/* BPC_Clear CMOS button */ null,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 8,
	/* BPC_eSATA/USB Combo connector */ null,
	/* BPC_eSATA 6Gb/s connector */ 2,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ 1,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 6,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out/Rear Speaker Out/Side Speaker Out/Line In/Line Out/Microphone',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE IT8728 chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_CPU/System fan speed control_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS&trade;',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ 'YES',
	/* UF_supp_Download Center */ 'YES',
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ 'YES',
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_EasyTune_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* UF_supp_Smart 6™ */ 'YES',
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ 'YES',
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ 'YES',
	/* UF_supp_TouchBIOS */ 'YES',
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ null,
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft&reg; Windows 8/7/Vista/XP',
	/* Form Factor */ 'ATX Form Factor; 30.5cm x 24.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD3/1.jpg',
	/* img_2 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD3/2.jpg',
	/* img_3 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD3/3.jpg',
	/* img_4 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD3/4.jpg',
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/products/motherboard/brand/GIGABYTE_LOGO.png',
	/* img_chipset */ 'images/products/motherboard/brand/INTEL_X79_chipset.png',
	/* price */ '625,000'
);

INSERT INTO motherboards VALUES (
	/* product_id */ null,
	/* motherboard_id */ 4,
	/* p_cat` */ 'motherboard',
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UD7',
	/* rev */ 1.0,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_company */ 'INTEL',
	/* C_socket */ '2011',
	/* C_cpuSupp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_cpuSupp_detail_2 */ 'L3 cache varies with CPU',
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 4,
	/* M_ddr3_upTo */ 32,
	/* M_ddr3_bus */ '2400/2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than 4 GB.',
	/* M_upTo */ 32,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC898',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ 'YES',
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* LAN_chip_1 */ 'Intel GbE LAN (10/100/1000 Mbit)',
	/* LAN_chip_2 */ null,
	/* WCM_detail_1 */ 'Wi-Fi 802.11 b/g/n',
	/* WCM_detail_2 */ 'Bluetooth 4.0, 3.0+HS, 2.1+EDR',
	/* ES_pcie_x16_16x_num */ 2,
	/* ES_pcie_x16_16x_name */ 'PCIEX16_1, PCIEX16_2',
	/* ES_pcie_x16_16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16 slot.',
	/* ES_pcie_x16_8x_num */ 2,
	/* ES_pcie_x16_8x_name */ 'PCIEX8_1, PCIEX8_2',
	/* ES_pcie_x16_8x_comment */ 'The PCIEX8_2 slot shares bandwidth with the PCIEX16_2 slot. When the PCIEX8_2 slot is populated, the PCIEX16_2 slot will operate at up to x8 mode.',
	/* ES_pcie_x16_4x_num */ null,
	/* ES_pcie_x16_4x_name */ null,
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 3,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci */ null,
	/* Multi-Graphics Technology */ 'Support for 4-Way/3-Way/2-Way AMD CrossFireX™/NVIDIA SLI technology.',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/3/4/5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2_name */ 'Marvell 88SE9172',
	/* SI_chip-2_num */ 1,
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'GSATA3.6/7/8/9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ null,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ null,
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ null,
	/* SI_chip-2_esata_6Gb/s_connector_comment */ null,
	/* SI_chip-2_raid_supp */ 'RAID 0, RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_port on the back panel */ 8,
	/* USB_chip-1_port on the back panel_comment */ null,
	/* USB_chip-1_port available through the internal USB header */ 6,
	/* USB_chip-2_name */ 'Fresco FL1009',
	/* USB_chip-2_num */ 2,
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_port on the back panel */ 2,
	/* USB_chip-2_port available through the internal USB header */ 2,
	/* USB_chip-2_comment */ null,
	/* USB_chip-3_name */ null,
	/* USB_chip-3_num */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ null,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ null,
	/* IEEE_1394_upTo */ null,
	/* IEEE_1394_ver */ null,
	/* IEEE_1394_port on the back panel */ null,
	/* IEEE 1394_port available through the internal IEEE 1394a header */ null,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 2,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ 2,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_SAS 3Gb/s connector */ null,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 6,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ null,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ 1,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ 1,
	/* IIOC_reset button */ 1,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ 1,
	/* IIOC_CPU BCLK Down button */ 1,
	/* IIOC_CPU BCLK Up button */ 1,
	/* IIOC_CPU Ratio Down button */ 1,
	/* IIOC_CPU Ratio Up button */ 1,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ 1,
	/* BPC_BIOS switch button */ 1,
	/* BPC_Clear CMOS button */ 1,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 8,
	/* BPC_eSATA/USB Combo connector */ null,
	/* BPC_eSATA 6Gb/s connector */ null,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ null,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 5,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out, Rear Speaker Out, Side Speaker Out, Line In, Mic In, Line Out',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE IT8728 chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_CPU/System fan speed control_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS&trade;',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ 'YES',
	/* UF_supp_Download Center */ 'YES',
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ 'YES',
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_EasyTune_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* UF_supp_Smart 6™ */ 'YES',
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ 'YES',
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ 'YES',
	/* UF_supp_TouchBIOS */ 'YES',
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ null,
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft&reg; Windows 8/7/Vista/XP',
	/* Form Factor */ 'XL-ATX Form Factor; 32.4cm x 25.3cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD7/1.jpg',
	/* img_2 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD7/2.jpg',
	/* img_3 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD7/3.jpg',
	/* img_4 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD7/4.jpg',
	/* img_5 */ 'images/products/motherboard/GIGABYTE/GA-X79-UD7/5.jpg',
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/products/motherboard/brand/GIGABYTE_LOGO.png',
	/* img_chipset */ 'images/products/motherboard/brand/INTEL_X79_chipset.png',
	/* price */ '840,000'
);

INSERT INTO motherboards VALUES (
	/* product_id */ null,
	/* motherboard_id */ 5,
	/* p_cat` */ 'motherboard',
	/* company */ 'GIGABYTE',
	/* model */ 'G1.Assassin 2',
	/* rev */ 1.0,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_company */ 'INTEL',
	/* C_socket */ '2011',
	/* C_cpuSupp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_cpuSupp_detail_2 */ 'L3 cache varies with CPU',
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 4,
	/* M_ddr3_upTo */ 32,
	/* M_ddr3_bus */ '2400/2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than 4 GB.',
	/* M_upTo */ 32,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Creative CA20K2',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ null,
	/* A_supp_eax®_advanced_hd™_5.0 */ 'YES',
	/* A_supp_x-fi_xtreme_fidelity® */ 'YES',
	/* LAN_chip_1 */ 'Bigfoot Killer E2100 chip (10/100/1000 Mbit)',
	/* LAN_chip_2 */ null,
	/* WCM_detail_1 */ 'Wi-Fi 802.11 b/g/n',
	/* WCM_detail_2 */ 'Bluetooth 4.0, 3.0+HS, 2.1+EDR',
	/* ES_pcie_x16_16x_num */ 2,
	/* ES_pcie_x16_16x_name */ 'PCIEX16_1/PCIEX16_2',
	/* ES_pcie_x16_16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16_1 slot; if you are installing two PCI Express graphics cards, it is recommended that you install them in the PCIEX16_1 and PCIEX16_2 slots.',
	/* ES_pcie_x16_8x_num */ 1,
	/* ES_pcie_x16_8x_name */ 'PCIEX8',
	/* ES_pcie_x16_8x_comment */ null,
	/* ES_pcie_x16_4x_num */ null,
	/* ES_pcie_x16_4x_name */ null,
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci */ 1,
	/* Multi-Graphics Technology */ 'Support for 3-Way/2-Way AMD CrossFireX™ / NVIDIA SLI technology.',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/SATA2.5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_comment */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2_name */ 'Marvell 88SE9172',
	/* SI_chip-2_num */ 2,
	/* SI_chip-2_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'GSATA3.6/GSATA3.7',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ 'eSATA/USB Combo on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_comment */ null,
	/* SI_chip-2_raid_supp */ 'RAID 0, RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_port on the back panel */ 8,
	/* USB_chip-1_port on the back panel_comment */ 'including 2 eSATA/USB Combo',
	/* USB_chip-1_port available through the internal USB header */ 6,
	/* USB_chip-2_name */ 'Fresco FL1009',
	/* USB_chip-2_num */ 2,
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_port on the back panel */ 2,
	/* USB_chip-2_port available through the internal USB header */ 2,
	/* USB_chip-2_comment */ null,
	/* USB_chip-3_name */ null,
	/* USB_chip-3_num */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ null,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ null,
	/* IEEE_1394_upTo */ null,
	/* IEEE_1394_ver */ null,
	/* IEEE_1394_port on the back panel */ null,
	/* IEEE_1394_port available through the internal IEEE 1394a header */ null,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 4,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_SAS 3Gb/s connector */ null,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ null,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ 1,
	/* BPC_BIOS switch button */ 1,
	/* BPC_Clear CMOS button */ 1,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 6,
	/* BPC_eSATA/USB Combo connector */ 2,
	/* BPC_eSATA 6Gb/s connector */ null,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ null,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 5,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out, Rear Speaker Out, Side Speaker Out, Line In/Mic In, Line Out',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE IT8728 chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_CPU/System fan speed control_comment */ ' Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS&trade;',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ 'YES',
	/* UF_supp_Download Center */ 'YES',
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ 'YES',
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_EasyTune_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* UF_supp_Smart 6™ */ 'YES',
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ 'YES',
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ 'YES',
	/* UF_supp_TouchBIOS */ 'YES',
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ null,
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft&reg; Windows 7/Vista/XP',
	/* Form Factor */ 'E-ATX Form Factor; 30.5cm x 26.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/products/motherboard/GIGABYTE/G1.Assassin 2/1.jpg',
	/* img_2 */ 'images/products/motherboard/GIGABYTE/G1.Assassin 2/2.jpg',
	/* img_3 */ 'images/products/motherboard/GIGABYTE/G1.Assassin 2/3.jpg',
	/* img_4 */ 'images/products/motherboard/GIGABYTE/G1.Assassin 2/4.jpg',
	/* img_5 */ 'images/products/motherboard/GIGABYTE/G1.Assassin 2/5.jpg',
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/products/motherboard/brand/GIGABYTE_LOGO.png',
	/* img_chipset */ 'images/products/motherboard/brand/INTEL_X79_chipset.png',
	/* price */ '940,000'
);

INSERT INTO motherboards VALUES (
	/* product_id */ null,
	/* motherboard_id */ 7,
	/* p_cat` */ 'motherboard',
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79S-UP5-WIFI',
	/* rev */ 1.1,
	/* chipset */ 'Intel&reg; C606 Express Chipset',
	/* C_company */ 'INTEL',
	/* C_socket */ '2011',
	/* C_cpuSupp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_cpuSupp_detail_2 */ 'L3 cache varies with CPU',
	/* C_cpuSupp_detail_3 */ null,
	/* C_cpuSupp_detail_4 */ null,
	/* C_cpuSupp_detail_5 */ null,
	/* M_ddr_slot */ null,
	/* M_ddr_upTo */ null,
	/* M_ddr_bus */ null,
	/* M_ddr_comment */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 8,
	/* M_ddr3_upTo */ 64,
	/* M_ddr3_bus */ '2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to a Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than the size of the physical memory installed.',
	/* M_upTo */ 64,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ 'YES',
	/* M_supp_non-ecc_memory_modules */ null,
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC898',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ null,
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* LAN_chip_1 */ 'Intel GbE LAN chip (10/100/1000 Mbit) (LAN1)',
	/* LAN_chip_2 */ 'Realtek GbE LAN chip (10/100/1000 Mbit) (LAN2)',
	/* WCM_detail_1 */ 'Wi-Fi 802.11 a/b/g/n, Supports 2.4/5 GHz Dual-Band',
	/* WCM_detail_2 */ 'Bluetooth 4.0, 3.0+HS, 2.1+EDR',
	/* ES_pcie_x16_16x_num */ 2,
	/* ES_pcie_x16_16x_name */ 'PCIEX16_1, PCIEX16_2',
	/* ES_pcie_x16_16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16_1 slot; if you are installing two PCI Express graphics cards, it is recommended that you install them in the PCIEX16_1 and PCIEX16_2 slots.',
	/* ES_pcie_x16_8x_num */ 1,
	/* ES_pcie_x16_8x_name */ 'PCIEX8',
	/* ES_pcie_x16_8x_comment */ 'The PCIEX8 slot shares bandwidth with the PCIEX16_2 slot. When the PCIEX8 slot is populated, the PCIEX16_2 slot will operate at up to x8 mode.',
	/* ES_pcie_x16_4x_num */ 1,
	/* ES_pcie_x16_4x_name */ 'PCIEX4',
	/* ES_pcie_x16_4x_comment */ null,
	/* ES_pcie_x16_comment */ 'The PCIEX16, PCIEX8, and PCIEX4 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 1,
	/* ES_pcie_x1_comment */ 'The PCIEX1 slot conforms to PCI Express 2.0 standard.',
	/* ES_pci */ 1,
	/* Multi-Graphics Technology */ 'Support for 3-Way/2-Way AMD CrossFireX™/NVIDIA SLI technology',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/SATA2.5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ ' RAID 0, RAID 1, RAID 5, RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ 8,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ 'SAS2.0/SAS2.7',
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ '8 SAS 3Gb/s devices',
	/* SI_chip-1_sas_3Gb/s_connector_comment */ 'The SAS connectors do not support optical drives.',
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ ' RAID 0, RAID 1, RAID 10',
	/* SI_chip-2_name */ 'Marvell 88SE9172',
	/* SI_chip-2_num */ 1,
	/* SI_chip-2_sata_6Gb/s_connector_num */ null,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ null,
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ null,
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver/info */ 'on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_comment */ 'including 1 eSATA/USB Combo',
	/* SI_chip-2_raid_supp */ 'RAID 0, RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* SI_sata_6Gb/s_connector_num */ null,
	/* SI_sata_3Gb/s_connector_num */ null,
	/* SI_sas_3Gb/s_connector_num */ null,
	/* SI_esata_6Gb/s_connector_num */ null,
	/* USB_chip-1_upTo */ 12,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_port on the back panel */ 6,
	/* USB_chip-1_port on the back panel_comment */ 'including 1 eSATA/USB Combo',
	/* USB_chip-1_port available through the internal USB header */ 6,
	/* USB_chip-2_name */ 'VIA VL800',
	/* USB_chip-2_num */ 1,
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_port on the back panel */ 4,
	/* USB_chip-2_port available through the internal USB header */ null,
	/* USB_chip-2_comment */ 'Due to a Windows 7 limitation, please connect your USB device(s) to the USB 2.0/1.1 port(s) before the VIA USB 3.0 controller driver is installed.',
	/* USB_chip-3_name */ 'Fresco FL1009',
	/* USB_chip-3_num */ 1,
	/* USB_chip-3_upTo */ 2,
	/* USB_chip-3_ver */ 'USB 3.0/2.0',
	/* USB_chip-3_port on the back panel */ null,
	/* USB_chip-3_port available through the internal USB header */ 2,
	/* USB_2.0/1.1 */ null,
	/* USB_3.0/2.0 */ null,
	/* IEEE_1394_chip */ 'VT6308',
	/* IEEE_1394_upTo */ 2,
	/* IEEE_1394_ver */ 'IEEE 1394a',
	/* IEEE_1394_port on the back panel */ 1,
	/* IEEE_1394_port available through the internal IEEE 1394a header */ 1,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 2,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_SAS 3Gb/s connector */ 8,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ 1,
	/* IIOC_serial port header */ null,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ 1,
	/* IIOC_reset button */ 1,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ 1,
	/* BPC_BIOS switch button */ 1,
	/* BPC_Clear CMOS button */ 1,
	/* BPC_IEEE 1394a port */ 1,
	/* BPC_USB 3.0/2.0 port */ 4,
	/* BPC_USB 2.0/1.1 port */ 5,
	/* BPC_eSATA/USB Combo connector */ 1,
	/* BPC_eSATA 6Gb/s connector */ 1,
	/* BPC_RJ-45 port */ 2,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ null,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 5,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out, Rear Speaker Out, Line In, Line Out, Mic In',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE I/O Controller Chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_CPU/System fan speed control_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS&trade;',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ null,
	/* UF_supp_Download Center */ null,
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ null,
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_EasyTune_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* UF_supp_Smart 6™ */ null,
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ null,
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ null,
	/* UF_supp_TouchBIOS */ null,
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ 'YES',
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft&reg; Windows 8/7/Vista',
	/* Form Factor */ 'E-ATX Form Factor; 30.5cm x 26.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/products/motherboard/GIGABYTE/GA-X79S-UP5-WIFI/1.jpg',
	/* img_2 */ 'images/products/motherboard/GIGABYTE/GA-X79S-UP5-WIFI/2.jpg',
	/* img_3 */ 'images/products/motherboard/GIGABYTE/GA-X79S-UP5-WIFI/3.jpg',
	/* img_4 */ 'images/products/motherboard/GIGABYTE/GA-X79S-UP5-WIFI/4.jpg',
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/products/motherboard/brand/GIGABYTE_LOGO.png',
	/* img_chipset */ 'images/products/motherboard/brand/INTEL_C600-Series_chipset.png',
	/* price */ '780,000'
);