INSERT INTO cpu VALUES (
	/* id */ null,
	/* p_cat` */ 'cpu',
	/* company */ 'Intel&reg;',
	/* model */ 'Core&trade; i7-4771',
	/* code name */ 'Haswell',
	/* E_Status */ 'Launched',
	/* E_Launch Date */ "Q2'13",
	/* E_Processor Number */ 'i7-4771',
	/* E_# of Cores */ 4,
	/* E_# of Threads */ 8,
	/* E_Clock Speed */ '3.5 GHz',
	/* E_Max Turbo Frequency */ '3.9 GHz',
	/* E_Cache */ '8 MB',
	/* E_Intel® Smart Cache */ null,
	/* E_# of QPI Links */ 0,
	/* E_DMI2 */ null,
	/* E_Instruction Set */ '64-bit',
	/* E_Instruction Set Extensions */ 'SSE 4.1/4.2, AVX 2.0',
	/* E_Embedded Options Available */ 'NO',
	/* E_Lithography */ '22 nm',
	/* E_Max TDP */ '84 W',
	/* E_Thermal Solution Specification */ 'PCG 2013D',
	/* E_Recommended Customer Price_BOX */ '$320,00',
	/* E_Recommended Customer Price_TRAY */ '$314,00',
	/* MS_Max Memory Size (dependent on memory type) */ '32 GB',
	/* MS_Memory Types */ 'DDR3-1333/1600',
	/* MS_# of Memory Channels */ 2,
	/* MS_Max Memory Bandwidth */ '25.6 GB/s',
	/* MS_ECC Memory Supported ‡ */ 'NO',
	/* GS_Processor Graphics ‡ */ 'Intel&reg; HD Graphics 4600',
	/* GS_Graphics Base Frequency */ '350 MHz',
	/* GS_Graphics Max Dynamic Frequency */ '1.2 GHz',
	/* GS_Intel® Quick Sync Video */ 'YES',
	/* GS_Intel® InTru™ 3D Technology */ 'YES',
	/* GS_Intel® Insider™ */ 'YES',
	/* GS_Intel® Wireless Display */ 'YES',
	/* GS_Intel® Clear Video HD Technology */ null,
	/* GS_# of Displays Supported ‡ */ null,
	/* GS_Intel® Flexible Display Interface (Intel® FDI) */ null,
	/* EO_PCI Express Revision */ '3.0',
	/* EO_PCI Express Configurations ‡ */ 'Up to 1x16, 2x8, 1x8/2x4',
	/* EO_Max # of PCI Express Lanes */ 16,
	/* PS_Max CPU Configuration */ 1,
	/* PS_TCASE */ '72°C',
	/* PS_Package Size */ '37.5mm x 37.5mm',
	/* PS_Graphics and IMC Lithography */ '22nm',
	/* PS_Sockets Supported */ 'FCLGA1150, FCLGA1150, FCLGA1150',
	/* PS_Low Halogen Options Available */ 'See MDDS',
	/* AT_Intel® Turbo Boost Technology ‡ */ '2.0',
	/* AT_Intel® vPro Technology ‡ */ 'YES',
	/* AT_Intel® Hyper-Threading Technology ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology (VT-x) ‡ */ 'YES',
	/* AT_Intel® Virtualization Technology for Directed I/O (VT-d) ‡ */ 'YES',
	/* AT_Intel® VT-x with Extended Page Tables (EPT) ‡ */ 'YES',
	/* AT_Intel® TSX-NI ‡ */ 'YES',
	/* AT_Intel® 64 ‡ */ 'YES',
	/* AT_Idle States */ 'YES',
	/* AT_Enhanced Intel SpeedStep® Technology */ 'YES',
	/* AT_Thermal Monitoring Technologies */ 'YES',
	/* AT_Intel® Identity Protection Technology ‡ */ 'YES',
	/* AT_Intel® My WiFi Technology */ null,
	/* AT_Intel® Demand Based Switching */ null,
	/* AT_Intel® Smart Response Technology */ null,
	/* Intel® DPT_AES New Instructions */ 'YES',
	/* Intel® DPT_Secure Key */ 'YES',
	/* Intel® PPT_Trusted Execution Technology ‡ */ 'YES',
	/* Intel® PPT_Anti-Theft Technology */ 'YES',
	/* Intel® PPT_Execute Disable Bit ‡ */ 'YES',
	/* img_1 */ 'images/products/cpu/INTEL/4th Generation/Core i7/i7-4771/i7-4771.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_brand */ 'images/products/cpu/brand/INTEL_LOGO.png',
	/* img_generation */ 'images/products/cpu/INTEL/4th generation/4th.png',
	/* price */ '500,000'
);