# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Exref
email: mohammad.ahmadi1989@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  These are my examples and references that I alway have to lookup before doing anything.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "m-ahmadi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  m-ahmadi

#-----------------------------------------------------------------------------------------------------------
# with this, you can remove layout from the front matter of all pages and posts.
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"