/*!40101 SET NAMES utf8 */;
DROP DATABASE IF EXISTS `p`;
CREATE DATABASE IF NOT EXISTS `p` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `p`;
GRANT ALL PRIVILEGES ON p.* TO 'PC-Fantasy'@'localhost' IDENTIFIED BY 'php1020315106016php';